# Generated by Django 6.1 on 2026-08-14 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='nome')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('logo', models.ImageField(blank=True, upload_to='stores/logos/', verbose_name='logótipo')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='telefone')),
                ('whatsapp', models.CharField(blank=True, max_length=30, verbose_name='WhatsApp')),
                ('province', models.CharField(blank=True, max_length=80, verbose_name='província')),
                ('municipality', models.CharField(blank=True, max_length=100, verbose_name='município')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovada'), ('suspended', 'Suspensa')], default='pending', max_length=20, verbose_name='estado')),
                ('featured', models.BooleanField(default=False, verbose_name='em destaque')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stores', to=settings.AUTH_USER_MODEL, verbose_name='proprietário')),
            ],
            options={
                'verbose_name': 'loja',
                'verbose_name_plural': 'lojas',
                'ordering': ['-featured', 'name'],
            },
        ),
    ]
