# Generated by Django 6.1 on 2026-08-14 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_name', models.CharField(max_length=160, verbose_name='nome proposto')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('phone', models.CharField(max_length=30, verbose_name='telefone')),
                ('whatsapp', models.CharField(blank=True, max_length=30, verbose_name='WhatsApp')),
                ('province', models.CharField(max_length=80, verbose_name='província')),
                ('municipality', models.CharField(max_length=100, verbose_name='município')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovada'), ('rejected', 'Rejeitada')], default='pending', max_length=20, verbose_name='estado')),
                ('review_note', models.TextField(blank=True, verbose_name='nota de análise')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='analisada em')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='store_applications', to=settings.AUTH_USER_MODEL, verbose_name='candidato')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_store_applications', to=settings.AUTH_USER_MODEL, verbose_name='analisada por')),
            ],
            options={
                'verbose_name': 'candidatura de loja',
                'verbose_name_plural': 'candidaturas de lojas',
                'ordering': ['-created_at'],
            },
        ),
    ]
