# Generated by Django 6.1 on 2026-08-15 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('multicaixa_express', 'Multicaixa Express'), ('unitel_money', 'Unitel Money'), ('paypay', 'PayPay')], max_length=32, verbose_name='método')),
                ('status', models.CharField(choices=[('created', 'Criada'), ('pending', 'Pendente'), ('succeeded', 'Concluída'), ('failed', 'Falhou'), ('cancelled', 'Cancelada')], default='created', max_length=16, verbose_name='estado')),
                ('provider_reference', models.CharField(blank=True, max_length=160, verbose_name='referência do provedor')),
                ('message', models.CharField(blank=True, max_length=255, verbose_name='mensagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_attempts', to='orders.order', verbose_name='pedido')),
            ],
            options={
                'verbose_name': 'tentativa de pagamento',
                'verbose_name_plural': 'tentativas de pagamento',
                'ordering': ['-created_at'],
            },
        ),
    ]
