# Generated by Django 4.2.30 on 2026-09-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('multicaixa_express', 'Multicaixa Express'), ('unitel_money', 'Unitel Money'), ('paypay', 'PayPay'), ('kyami_pay', 'Kyami Pay')], max_length=32, unique=True, verbose_name='provedor')),
                ('is_active', models.BooleanField(default=False, verbose_name='ativo')),
                ('is_sandbox', models.BooleanField(default=True, verbose_name='modo sandbox')),
                ('client_id', models.CharField(blank=True, max_length=255, verbose_name='Client ID / API Key')),
                ('client_secret', models.CharField(blank=True, max_length=255, verbose_name='Client Secret / Secret Key')),
                ('merchant_id', models.CharField(blank=True, max_length=255, verbose_name='Merchant ID / POS ID')),
                ('api_base_url', models.URLField(blank=True, verbose_name='URL base da API')),
                ('webhook_secret', models.CharField(blank=True, max_length=255, verbose_name='Webhook Secret / HMAC Key')),
                ('extra_config', models.JSONField(blank=True, default=dict, verbose_name='configuração extra')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'configuração de provedor de pagamento',
                'verbose_name_plural': 'configurações de provedores de pagamento',
            },
        ),
        migrations.AlterField(
            model_name='paymentattempt',
            name='method',
            field=models.CharField(choices=[('multicaixa_express', 'Multicaixa Express'), ('unitel_money', 'Unitel Money'), ('paypay', 'PayPay'), ('kyami_pay', 'Kyami Pay')], max_length=32, verbose_name='método'),
        ),
    ]
