# Generated by Django 6.1 on 2026-08-14 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('image', models.ImageField(blank=True, upload_to='catalog/categories/', verbose_name='imagem')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ordem')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='nome')),
                ('slug', models.SlugField(verbose_name='slug')),
                ('sku', models.CharField(max_length=80, verbose_name='SKU')),
                ('short_description', models.CharField(blank=True, max_length=240, verbose_name='descrição curta')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('image', models.ImageField(blank=True, upload_to='catalog/products/', verbose_name='imagem')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='preço')),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='preço anterior')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='stock')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('active', 'Ativo'), ('out_of_stock', 'Sem stock'), ('suspended', 'Suspenso')], default='draft', max_length=20, verbose_name='estado')),
                ('featured', models.BooleanField(default=False, verbose_name='em destaque')),
                ('is_new', models.BooleanField(default=True, verbose_name='novidade')),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='avaliação')),
                ('review_count', models.PositiveIntegerField(default=0, verbose_name='número de avaliações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='categoria')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='stores.store', verbose_name='loja')),
            ],
            options={
                'verbose_name': 'produto',
                'verbose_name_plural': 'produtos',
                'ordering': ['-featured', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('store', 'sku'), name='unique_product_sku_per_store'), models.UniqueConstraint(fields=('store', 'slug'), name='unique_product_slug_per_store')],
            },
        ),
    ]
