# Generated by Django 6.1 on 2026-08-15 06:29

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('stores', '0002_storeapplication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='chave da sessão')),
                ('order_number', models.CharField(max_length=24, unique=True, verbose_name='número do pedido')),
                ('customer_name', models.CharField(max_length=160, verbose_name='nome do cliente')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='email do cliente')),
                ('customer_phone', models.CharField(max_length=40, verbose_name='telefone do cliente')),
                ('province', models.CharField(max_length=80, verbose_name='província')),
                ('municipality', models.CharField(max_length=100, verbose_name='município')),
                ('address', models.CharField(max_length=240, verbose_name='morada')),
                ('address_details', models.CharField(blank=True, max_length=240, verbose_name='detalhes da morada')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='subtotal')),
                ('shipping_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='envio')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='total')),
                ('currency', models.CharField(default='AOA', max_length=3, verbose_name='moeda')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('awaiting_payment', 'A aguardar pagamento'), ('paid', 'Pago'), ('processing', 'Em preparação'), ('shipped', 'Enviado'), ('completed', 'Concluído'), ('cancelled', 'Cancelado')], default='pending', max_length=24, verbose_name='estado')),
                ('payment_status', models.CharField(choices=[('not_started', 'Não iniciado'), ('pending', 'Pendente'), ('paid', 'Pago'), ('failed', 'Falhou'), ('refunded', 'Reembolsado')], default='not_started', max_length=24, verbose_name='estado do pagamento')),
                ('payment_method', models.CharField(blank=True, max_length=40, verbose_name='método de pagamento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='utilizador')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='subtotal da loja')),
                ('shipping_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='envio da loja')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='total da loja')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('awaiting_payment', 'A aguardar pagamento'), ('paid', 'Pago'), ('processing', 'Em preparação'), ('shipped', 'Enviado'), ('completed', 'Concluído'), ('cancelled', 'Cancelado')], default='pending', max_length=24, verbose_name='estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_orders', to='orders.order')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='store_orders', to='stores.store')),
            ],
            options={
                'verbose_name': 'pedido da loja',
                'verbose_name_plural': 'pedidos das lojas',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=180, verbose_name='nome do produto')),
                ('sku', models.CharField(max_length=80, verbose_name='SKU')),
                ('store_name', models.CharField(max_length=160, verbose_name='nome da loja')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='preço unitário')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantidade')),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='total da linha')),
                ('image', models.CharField(blank=True, max_length=255, verbose_name='imagem')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.product')),
                ('store_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.storeorder')),
            ],
            options={
                'verbose_name': 'linha do pedido',
                'verbose_name_plural': 'linhas dos pedidos',
            },
        ),
        migrations.AddConstraint(
            model_name='storeorder',
            constraint=models.UniqueConstraint(fields=('order', 'store'), name='unique_store_order'),
        ),
    ]
