# Generated by Django 6.1 on 2026-08-16 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement', models.CharField(choices=[('hero', 'Hero principal'), ('promotion', 'Promoção'), ('service', 'Serviço')], max_length=24, verbose_name='posição')),
                ('title', models.CharField(max_length=180, verbose_name='título')),
                ('subtitle', models.CharField(blank=True, max_length=240, verbose_name='subtítulo')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('button_label', models.CharField(blank=True, max_length=80, verbose_name='texto do botão')),
                ('button_url', models.CharField(blank=True, max_length=300, verbose_name='URL do botão')),
                ('image', models.ImageField(blank=True, upload_to='homepage/banners/', verbose_name='imagem')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='início')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='fim')),
            ],
            options={
                'verbose_name': 'banner da homepage',
                'verbose_name_plural': 'banners da homepage',
                'ordering': ['placement', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomepageLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement', models.CharField(choices=[('top', 'Barra superior'), ('header', 'Cabeçalho'), ('category', 'Categorias'), ('footer', 'Rodapé')], max_length=24, verbose_name='posição')),
                ('label', models.CharField(max_length=100, verbose_name='texto')),
                ('url', models.CharField(max_length=300, verbose_name='URL')),
                ('icon', models.CharField(blank=True, max_length=80, verbose_name='ícone')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'link da homepage',
                'verbose_name_plural': 'links da homepage',
                'ordering': ['placement', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomepageTextBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True, verbose_name='chave')),
                ('title', models.CharField(max_length=180, verbose_name='título')),
                ('subtitle', models.CharField(blank=True, max_length=240, verbose_name='subtítulo')),
                ('body', models.TextField(blank=True, verbose_name='conteúdo')),
                ('button_label', models.CharField(blank=True, max_length=80, verbose_name='texto do botão')),
                ('button_url', models.CharField(blank=True, max_length=300, verbose_name='URL do botão')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'bloco de texto da homepage',
                'verbose_name_plural': 'blocos de texto da homepage',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='default', max_length=40, unique=True, verbose_name='chave')),
                ('site_name', models.CharField(default='Marketplace Angola', max_length=160, verbose_name='nome do site')),
                ('tagline', models.CharField(blank=True, max_length=240, verbose_name='frase principal')),
                ('shipping_message', models.CharField(blank=True, max_length=240, verbose_name='mensagem de envio')),
                ('support_phone', models.CharField(blank=True, max_length=80, verbose_name='telefone de suporte')),
                ('support_email', models.EmailField(blank=True, max_length=254, verbose_name='email de suporte')),
                ('contact_address', models.CharField(blank=True, max_length=240, verbose_name='morada')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter')),
                ('whatsapp_url', models.URLField(blank=True, verbose_name='WhatsApp')),
                ('newsletter_title', models.CharField(blank=True, max_length=160, verbose_name='título da newsletter')),
                ('newsletter_description', models.CharField(blank=True, max_length=240, verbose_name='descrição da newsletter')),
                ('currency_code', models.CharField(default='AOA', max_length=8, verbose_name='código da moeda')),
                ('currency_symbol', models.CharField(default='Kz', max_length=8, verbose_name='símbolo da moeda')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'configuração do site',
                'verbose_name_plural': 'configuração do site',
            },
        ),
    ]
